[package]
name = "iedit_core"
version = "0.1.1"
edition = "2024"

[dependencies]
iedit_macros = { workspace = true }
regex-lite = "0.1.8"
termion = { workspace = true }

[[bin]]
name = "iedit"
path = "src/main.rs"
