name: Bump Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Read version
        id: read_version
        run: |
          set -e
          CARGO_TOML="iedit_core/Cargo.toml"
          if [ -f "$CARGO_TOML" ]; then
            ver=$(sed -n 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' "$CARGO_TOML" | head -n1)
          else
            ver=""
          fi
          if [ -z "$ver" ]; then
            echo "No version found in $CARGO_TOML; defaulting to 0.0.0" >&2
            ver="0.0.0"
          fi
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Calculate SHAs and update formula
        env:
          VERSION: ${{ steps.read_version.outputs.version }}
        run: |
          set -euo pipefail

          VERSION="${VERSION}"

          MACOS_X86_URL="https://github.com/gooplancton/iedit/releases/download/v${VERSION}/iedit-macos-x86_64"
          MACOS_ARM_URL="https://github.com/gooplancton/iedit/releases/download/v${VERSION}/iedit-macos-arm64"
          LINUX_URL="https://github.com/gooplancton/iedit/releases/download/v${VERSION}/iedit-linux"

          echo "Fetching and hashing:"
          echo "  $MACOS_X86_URL"
          echo "  $MACOS_ARM_URL"
          echo "  $LINUX_URL"

          MACOS_X86_SHA=$(curl -fsSL "$MACOS_X86_URL" | sha256sum | cut -d' ' -f1)
          MACOS_ARM_SHA=$(curl -fsSL "$MACOS_ARM_URL" | sha256sum | cut -d' ' -f1)
          LINXU_SHA=$(curl -fsSL "$LINUX_URL" | sha256sum | cut -d' ' -f1)

          echo "macos x86 sha: $MACOS_X86_SHA"
          echo "macos arm sha: $MACOS_ARM_SHA"
          echo "linux sha: $LINUX_SHA"

          export VERSION MACOS_X86_SHA MACOS_ARM_SHA LINUX_SHA

          ruby <<'EOF'
          formula_file = 'Formula/iedit.rb'
          content = File.read(formula_file)

          # update version (robust to non-numeric segments)
          content.gsub!(/version\s+["'][^"']+["']/, "version \"#{ENV['VERSION']}\"")

          content.gsub!(/MACOS_X86_URL = ["']\S+["']/, "MACOS_X86_URL = \"#{ENV['MACOS_X86_URL']}\"")
          content.gsub!(/MACOS_X86_SHA = ["']\S+["']/, "MACOS_X86_SHA = \"#{ENV['MACOS_X86_SHA']}\"")

          content.gsub!(/MACOS_ARM_URL = ["']\S+["']/, "MACOS_ARM_URL = \"#{ENV['MACOS_ARM_URL']}\"")
          content.gsub!(/MACOS_ARM_SHA = ["']\S+["']/, "MACOS_ARM_SHA = \"#{ENV['MACOS_ARM_SHA']}\"")

          content.gsub!(/LINUX_URL = ["']\S+["']/, "LINUX_URL = \"#{ENV['LINUX_URL']}\"")
          content.gsub!(/LINUX_SHA = ["']\S+["']/, "LINUX_SHA = \"#{ENV['LINUX_SHA']}\"")

          File.write(formula_file, content)
          EOF

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/iedit.rb

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: updated homebrew formula [skip ci]"
            git push
          fi
