name: Bump Homebrew Formula

on:
  release:
    types: [published]

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Read version
        id: read_version
        run: |
          set -e
          CARGO_TOML="iedit_core/Cargo.toml"
          if [ -f "$CARGO_TOML" ]; then
            ver=$(sed -n 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' "$CARGO_TOML" | head -n1)
          else
            ver=""
          fi
          if [ -z "$ver" ]; then
            echo "No version found in $CARGO_TOML; defaulting to 0.0.0" >&2
            ver="0.0.0"
          fi
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Calculate SHAs and update formula
        env:
          VERSION: ${{ steps.read_version.outputs.version }}
        run: |
          set -euo pipefail

          VERSION="${VERSION}"

          MACOS_X86_URL="https://github.com/gooplancton/iedit/releases/download/v${VERSION}/iedit-macos-x86_64"
          MACOS_ARM_URL="https://github.com/gooplancton/iedit/releases/download/v${VERSION}/iedit-macos-arm64"
          SRC_URL="https://github.com/gooplancton/iedit/archive/refs/tags/v${VERSION}"

          echo "Fetching and hashing:"
          echo "  $MACOS_X86_URL"
          echo "  $MACOS_ARM_URL"
          echo "  $SRC_URL"

          MACOS_X86_SHA=$(curl -fsSL "$MACOS_X86_URL" | sha256sum | cut -d' ' -f1)
          MACOS_ARM_SHA=$(curl -fsSL "$MACOS_ARM_URL" | sha256sum | cut -d' ' -f1)
          SRC_SHA=$(curl -fsSL "$SRC_URL" | sha256sum | cut -d' ' -f1)

          echo "macos x86 sha: $MACOS_X86_SHA"
          echo "macos arm sha: $MACOS_ARM_SHA"
          echo "src sha: $SRC_SHA"

          export VERSION MACOS_X86_SHA MACOS_ARM_SHA SRC_SHA

          ruby <<'EOF'
          formula_file = 'Formula/iedit.rb'
          content = File.read(formula_file)

          # update version (robust to non-numeric segments)
          content.gsub!(/version\s+["'][^"']+["']/, "version \"#{ENV['VERSION']}\"")

          # replace explicit placeholder checksums (adjust placeholders if your formula differs)
          content.gsub!(/sha256\s+["']REPLACE_WITH_ACTUAL_SHA256_FOR_x86_64_TAR_GZ["']/, "sha256 \"#{ENV['MACOS_X86_SHA']}\"")
          content.gsub!(/sha256\s+["']REPLACE_WITH_ACTUAL_SHA256_FOR_arm64_TAR_GZ["']/, "sha256 \"#{ENV['MACOS_ARM_SHA']}\"")
          content.gsub!(/sha256\s+["']REPLACE_WITH_SOURCE_TARBALL_SHA256["']/, "sha256 \"#{ENV['SRC_SHA']}\"")

          File.write(formula_file, content)
          EOF

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/iedit.rb

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: updated homebrew formula [skip ci]"
            git push
          fi
