pub enum CursorMovement {
    AbsolutePos((usize, usize)),
    Up(usize),
    Down(usize),
    Left(usize),
    Right(usize),
    NextWord,
    PreviousWord,
    NextParagraph,
    StartOfLine,
    EndOfLine,
    StartOfFile,
    EndOfFile,
    PreviousParagraph,
    MatchingParenthesis,
    NextOccurrenceOf(char),
    PreviousOccurrenceOf(char),
}
